#!/bin/bash

# PidgeonBot module
# send current discordian date

# defines the keywords in chat upon which the module should be invoked
local TRIGGER='":!ddate"';

pidgeonbot_module_ddate(){
	irc_cmd_msg "${REPLYTO}" "$(ddate)";
}
