#!/bin/bash

# PidgeonBot module ddate

# Interpreter will call function pidgeonbot_module_${FILENAME} when ${TRIGGER} is used in chat
# ${1}		FROM	caller
# ${2}		TO	channel name or botname respectivly
# ${3}		MSG	message sent
# ${4}		REPLYTO	

# define keywords upon which the module should be invoked
TRIGGER='":!ddate"|":!discordian"'; #surround in hard quotes

# function pidgeonbot_module_${FILENAME}
pidgeonbot_module_ddate(){
	irc_cmd_msg "${4}" ":$(ddate)";
}
