#!/bin/bash

# PidgeonBot module
# send message back to sender

# defines the keywords in chat upon which the module should be invoked
local TRIGGER='":!echo"|":!2ndecho"';

pidgeonbot_module_echo(){
	irc_cmd_msg "${REPLYTO}" "$MSG";
}
