#!/bin/bash

# PidgeonBot module gurr

TRIGGER='*g[u]*r[r]*';

pidgeonbot_module_gurr(){
	irc_cmd_msg "${4}" ":$(util_generate_gurr)";
}

util_generate_gurr(){
    local countU=$(( 1 + $(( $RANDOM % 5 ))));
    local countR=$(( 2 + $(( $RANDOM % 3 ))));
    local i=0;
    local gurr="*g"
    for (( i=0 ; $i<$countU ; i++ ))
    do
      gurr="${gurr}u";
    done

    i=0;
    for (( i=0 ; $i<$countR ; i++ ))
    do
      gurr="${gurr}r";
    done
    gurr="${gurr}*"
    echo ${gurr}
}

