#!/bin/bash

## InterpreterBuilder

# Builds Interpreter based on modules in /modules/

$(rm Interpreter)
exec 5<> Interpreter

echo '#!/bin/bash' >&5
echo >&5
echo '# this files gets generated during runtime' >&5
echo >&5
echo 'irc_msg_interpret(){' >&5
echo '    case "$3" in' >&5
echo >&5

for f in $(ls modules | grep -v "~")
do
	. modules/${f}
	if [ -z "${TRIGGER}" ]; then
		continue
	fi
	echo "        ${TRIGGER} )" >&5
	echo "            . modules/${f}" >&5
	echo "            pidgeonbot_module_${f} "'${1} ${2} ${3} ${4}' >&5
	echo "            ;;" >&5
	echo >&5
done
echo '        *)' >&5
echo '            ;;' >&5
echo '    esac' >&5
echo '}' >&5

exec 5>&-

