#!/bin/bash

# this files gets generated during runtime

irc_msg_interpret(){
    case "$3" in

        ":!ddate"|":!discordian" )
            . modules/ddate
            pidgeonbot_module_ddate ${1} ${2} ${3} ${4}
            ;;

        ":!feed" )
            . modules/feed
            pidgeonbot_module_feed ${1} ${2} ${3} ${4}
            ;;

        *g[u]*r[r]* )
            . modules/gurr
            pidgeonbot_module_gurr ${1} ${2} ${3} ${4}
            ;;

        ":!info" )
            . modules/info
            pidgeonbot_module_info ${1} ${2} ${3} ${4}
            ;;

        ":!modinfo" )
            . modules/modinfo
            pidgeonbot_module_modinfo ${1} ${2} ${3} ${4}
            ;;

        ":!polly" )
            . modules/polly
            pidgeonbot_module_polly ${1} ${2} ${3} ${4}
            ;;

        ":!hit"|":!slap" )
            . modules/slap
            pidgeonbot_module_slap ${1} ${2} ${3} ${4}
            ;;

        ":!usage" )
            . modules/usage
            pidgeonbot_module_usage ${1} ${2} ${3} ${4}
            ;;

        *)
            ;;
    esac
}
