#!/bin/bash

# this files gets generated during runtime

irc_msg_interpret(){
    case "$3" in

        ":!ddate"|":!discordian" )
            . modules/ddate
            pidgeonbot_module_ddate ${1} ${2} ${3} ${4}
            ;;

        *g[u]*r[r]* )
            . modules/gurr
            pidgeonbot_module_gurr ${1} ${2} ${3} ${4}
            ;;

        *)
            ;;
    esac
}
