#!/bin/bash

## IrcParser

irc_parse()
{
    local ORIG="$1";
    set $1;

    case "${2}" in
	NOTICE) 
	    irc_handle_notice "${ORIG}";
	    ;;
	PRIVMSG)
	    . MsgHandler
	    irc_handle_message "${ORIG}";
	    ;;
	JOIN)
	    . MsgHandler
	    irc_handle_join "${ORIG}";
	    ;;
	KICK) 
	    irc_handle_kick "${ORIG}";
	    ;;
	PART)
	    irc_handle_part "${ORIG}";
	    ;;
	NICK)
	    irc_handle_nick "${ORIG}";
	    ;;
    esac

    case "$1" in
	PING)
	    irc_cmd_pong "${ORIG}";
	    ;;
    esac

}
