#!/bin/bash

## MsgHandler

# Callback on receving a PRIVMSG

irc_msg_callback()
{
    echo "-Msg- ${1}/${2} ${3}";

    # identify if msg sent in private or channel
    local REPLYTO="";
    case "$2" in
        "$NICK" )
            REPLYTO="${1}";
            ;;
        *)
            REPLYTO="${2}";
            ;;
    esac

    # commands
    . Interpreter
    irc_msg_interpret ${1} ${2} ${3} ${REPLYTO};

	return;
    
}

irc_handle_message()
{
    local FULLMSG="$@";
    oldIFS="${IFS}";
    IFS=":!${IFS}";
    set $@;
    local FROM=$2;
    local TO=$5;
    IFS="${oldIFS}";
    set ${FULLMSG};
    shift ; shift ; shift;
    local MSG="$@";
    IFS="${oldIFS}";
    irc_msg_callback "${FROM}" "${TO}" "${MSG}";

    return 0;
}

util_generate_gurr(){
    local countU=$(( 1 + $(( $RANDOM % 5 ))));
    local countR=$(( 2 + $(( $RANDOM % 3 ))));
    local i=0;
    local gurr="*g"
    for (( i=0 ; $i<$countU ; i++ ))
    do
      gurr="${gurr}u";
    done

    i=0;
    for (( i=0 ; $i<$countR ; i++ ))
    do
      gurr="${gurr}r";
    done
    gurr="${gurr}*"
    echo ${gurr}
}

