#!/bin/bash

## MsgHandler

# Callback on receving a PRIVMSG

irc_msg_callback()
{
    local FROM="${1}";
    local TO="${2}";
    local MSG="${3}";

    echo "-Msg- ${FROM}/${TO} ${MSG}";

    # identify if msg sent in private or channel
    local SCOPE="";
    case "$2" in
        "$NICK" )
            SCOPE="PRIVATE";
            ;;
        *)
            SCOPE="PUBLIC";
            ;;
    esac

    # commands
    .  Interpreter
    irc_msg_interpret() ;

	return;
    
}

irc_handle_message()
{
    local FULLMSG="$@";
    oldIFS="${IFS}";
    IFS=":!${IFS}";
    set $@;
    local FROM=$2;
    local TO=$5;
    IFS="${oldIFS}";
    set ${FULLMSG};
    shift ; shift ; shift;
    local MSG="$@";
    IFS="${oldIFS}";
    irc_msg_callback "${FROM}" "${TO}" "${MSG}";

    return 0;
}
